apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: techtrends
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: project/helm
    repoURL: https://github.com/grasmuru/udacity-nd064-assignment1
    targetRevision: HEAD